"""empty message

Revision ID: acf527f39837
Revises: a11110f35a4d
Create Date: 2024-05-12 17:09:05.896274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf527f39837'
down_revision = 'a11110f35a4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homework_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('homework_id', sa.Integer(), nullable=False, comment='作业ID'),
    sa.Column('department', sa.String(length=100), nullable=False, comment='部门'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='姓名'),
    sa.Column('content', sa.Text(), nullable=False, comment='内容'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('homework_progress')
    # ### end Alembic commands ###
