"""empty message

Revision ID: d5f7c7d6e34a
Revises: 
Create Date: 2024-05-09 23:54:47.980646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5f7c7d6e34a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False, comment='账号'),
    sa.Column('password', sa.String(length=100), nullable=False, comment='密码'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='姓名'),
    sa.Column('role', sa.String(length=100), nullable=False, comment='角色'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
